#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive
KUBECTL_VERSION=${KUBECTL_VERSION:-v1.20.15}
HELM_VERSION=${HELM_VERSION:-3.5.2}
GOMPLATE_VERSION=${GOMPLATE_VERSION:-v3.11.4}
DOCKER_VERSION="5:20.10.13~3-0~debian-${DEBIAN_VERSION:-bullseye}"

apt-get update -qq
apt-get install -y --no-install-recommends \
    curl ca-certificates

echo "Installing Docker-ce-cli-${DOCKER_VERSION}"
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

apt-get update -qq
apt install -y docker-ce-cli="${DOCKER_VERSION}"

echo "Installing Helm-${HELM_VERSION}"
curl -Ls https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar zxf -
chmod +x linux-amd64/helm
mv linux-amd64/helm /usr/local/bin/
rm -rf linux-amd64/
helm version

echo "Installing kubectl-${KUBECTL_VERSION}"
curl -LsO https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
chmod +x kubectl
mv kubectl /usr/local/bin/kubectl
kubectl version --client=true

echo "Installing gomplate-${GOMPLATE_VERSION}"
curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/${GOMPLATE_VERSION}/gomplate_linux-amd64
chmod +x /usr/local/bin/gomplate
gomplate -v