# Configure chart to use dev registry

# Need an imagePullSecret to access dev registry
.pullSecret: &pullSecret
  pullSecrets:
    - name: dev-images-pull-secret

# This section should be greatly shortened once https://gitlab.com/gitlab-org/charts/gitlab/-/issues/1617
#   is addressed. For example: `global.image.repository=dev.gitlab.org:5005/gitlab/charts/components/images`
# This means we can likely remove this extra file and pass in extra arguments with $HELM_EXTRA_ARGS.
gitlab:
  gitlab-exporter:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/gitlab-exporter
      <<: *pullSecret
  gitaly:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/gitaly
      <<: *pullSecret
  gitlab-shell:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/gitlab-shell
      <<: *pullSecret
  migrations:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/gitlab-task-runner-ee
      <<: *pullSecret
  sidekiq:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/gitlab-sidekiq-ee
      <<: *pullSecret
  task-runner:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/gitlab-task-runner-ee
      <<: *pullSecret
  webservice:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/gitlab-webservice-ee
      <<: *pullSecret
    workhorse:
      image: dev.gitlab.org:5005/gitlab/charts/components/images/gitlab-workhorse-ee
      <<: *pullSecret

global:
  certificates:
    image:
      repository: dev.gitlab.org:5005/gitlab/charts/components/images/alpine-certificates
      <<: *pullSecret
