dependencies:
- name: gitlab
  version: '*.*.*'
- name: certmanager-issuer
  version: '*.*.*'
- name: minio
  version: '*.*.*'
- name: registry
  version: '*.*.*'
- name: cert-manager
  version: v1.12.16
  repository: https://charts.jetstack.io/
  condition: certmanager.install
  alias: certmanager
- name: prometheus
  version: 15.18.0
  repository: https://prometheus-community.github.io/helm-charts
  condition: prometheus.install
- name: postgresql
  version: 15.5.20
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.install
- name: gitlab-runner
  version: 0.74.1
  repository: https://charts.gitlab.io/
  condition: gitlab-runner.install
- name: redis
  version: 18.19.4
  repository: https://charts.bitnami.com/bitnami
  condition: redis.install
- name: nginx-ingress
  condition: nginx-ingress.enabled
  version: '*.*.*'
- name: nginx-ingress
  condition: nginx-ingress-geo.enabled
  version: '*.*.*'
  alias: nginx-ingress-geo
- name: gitlab-zoekt
  version: 1.8.1
  repository: https://charts.gitlab.io/
  condition: gitlab-zoekt.install
- name: gluon
  version: "0.5.14"
  repository: "oci://registry1.dso.mil/bigbang"
- name: traefik
  repository: https://helm.traefik.io/traefik
  condition: traefik.install
  version: 10.19.4
- name: kubernetes-ingress
  alias: haproxy
  version: 1.32.0
  condition: haproxy.install
  repository: https://haproxytech.github.io/helm-charts
