dependencies:
- name: gitlab
  version: '*.*.*'
- name: shared-secrets
  version: '*.*.*'
- name: certmanager-issuer
  version: '*.*.*'
- name: minio
  version: '*.*.*'
- name: registry
  version: '*.*.*'
- name: cert-manager
  version: 0.10.1
  repository: file://./charts/cert-manager-v0.10.1.tgz
  condition: certmanager.install
  alias: certmanager
- name: prometheus
  version: 10.0.0
  repository: file://./charts/prometheus-10.0.0.tgz
  condition: prometheus.install
- name: postgresql
  version: 8.9.4
  repository: file://./charts/postgresql-8.9.4.tgz
  condition: postgresql.install
- name: gitlab-runner
  version: 0.26.0
  repository: file://./charts/gitlab-runner-0.26.0.tgz
  condition: gitlab-runner.install
- name: grafana
  version: 4.0.1
  repository: file://./charts/grafana-4.0.1.tgz
  condition: global.grafana.enabled
- name: redis
  version: 11.3.4
  repository: file://./charts/redis-11.3.4.tgz
  condition: redis.install
- name: nginx-ingress
  condition: nginx-ingress.enabled
  version: '*.*.*'
- name: bb-test-lib
  version: 0.4.0
  repository: file://./charts/bb-test-lib-0.4.0.tgz