# https://docs.gitlab.com/charts/charts/globals#configure-postgresql-settings
# https://docs.gitlab.com/administration/postgresql/database_load_balancing/
global:
  psql:
    host: primary.db.example
    load_balancing:
      hosts:
      - secondary-1.db.example
      - secondary-2.db.example
postgresql:
  install: false
