{{- $sharedSecretValues := index .Values "shared-secrets" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "shared-secrets.jobname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
{{- if and $sharedSecretValues.enabled (not .Values.global.operator.enabled) }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        {{- include "gitlab.podLabels" . | nindent 8 }}
      annotations:
      {{- range $key, $value := $sharedSecretValues.annotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
    spec:
      {{- include "gitlab.nodeSelector" . | nindent 6 }}
      {{- if $sharedSecretValues.tolerations }}
      tolerations:
        {{- toYaml $sharedSecretValues.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ $sharedSecretValues.securityContext.runAsUser }}
        fsGroup: {{ $sharedSecretValues.securityContext.fsGroup }}
      {{- if $sharedSecretValues.rbac.create }}
      serviceAccountName: {{ template "shared-secrets.serviceAccountName" . }}
      {{- end }}
      restartPolicy: Never
      {{- include "pullsecrets" .Values.global.kubectl.image | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "gitlab.kubectl.image" . | quote }}
          command: ['/bin/bash', '/scripts/generate-secrets']
          {{ template "gitlab.imagePullPolicy" . }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: ssh
              mountPath: /etc/ssh
          resources:
            {{- toYaml $sharedSecretValues.resources | nindent 12 }}
      volumes:
      - name: scripts
        configMap:
          name: {{ template "shared-secrets.fullname" . }}
      - name: ssh
        emptyDir: {}
