{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled .Values.redis.install }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-ingress-redis
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector:
    matchLabels:
      app: redis
      release: "{{ .Release.Name }}"
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
      podSelector:
        matchLabels:
          app: prometheus
    ports:
    - port: 9121
      protocol: TCP
{{- end }}
