{{- $gitlabexporterenabled := index .Values "gitlab" "gitlab-exporter" "enabled" }}
{{- if and .Values.networkPolicies.enabled $gitlabexporterenabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: gitlab-exporter
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: 9168
      protocol: TCP
{{- end }}
