{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.gitalyEgress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-gitaly
  namespace: "{{ .Release.Namespace }}"
spec:
  podSelector: 
    matchLabels:
      app: gitaly
  policyTypes:
    - Egress
  egress:
    - ports:
      - port: 443
        protocol: TCP
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          - 169.254.169.254/32
{{- end }}
