{{- if and .Values.networkPolicies.enabled .Values.global.appConfig.omniauth.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-sso
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app: webservice
  policyTypes:
  - Egress
  egress:
    - ports:
      - port: 443
        protocol: TCP
{{- end }}
