{{- if and .Values.networkPolicies.enabled .Values.use_iam_profile }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-metadata-sidekiq
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: sidekiq
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 169.254.169.254/32
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-metadata-webservice
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: webservice
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 169.254.169.254/32
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-metadata-task-runner
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: task-runner
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 169.254.169.254/32
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-metadata-registry
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: registry
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 169.254.169.254/32        
{{- end }}