{{- if and .Values.networkPolicies.enabled .Values.istio.enabled .Values.istio.pages.enabled .Values.global.pages.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-istio-gitlab-pages
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchLabels:
      app: gitlab-pages
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: istio-controlplane
      podSelector:
        matchLabels:
          {{- toYaml .Values.istio.pages.ingressLabels | nindent 10}}
    ports:
    - port: 8090 # http-gitlab-pages targetPort
      protocol: TCP
{{- end }}