{{- if and .Values.networkPolicies.enabled .Values.monitoring.enabled .Values.redis.install }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-monitoring-redis-client
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: redis
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana 
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: 6379
      protocol: TCP
{{- end }}
