apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
 

  # TODO: lol
  # labels:
  #   istio-injection: enabled