apiVersion: v1
kind: PersistentVolume
metadata:
  name: PERSISTENT_VOLUME_NAME
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: VOLUME_SIZE
  storageClassName: CUSTOM_STORAGE_CLASS_NAME
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-xxxxxxxxx
# awsElasticBlockStore is deprecated in Kubernetes v1.17 and the container storage interface (CSI) is recommeded instead.
# If your cluster version is less than 1.17, use awsElasticBlockStore instead of CSI.
# For details, see https://kubernetes.io/docs/concepts/storage/volumes/ and https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi-migration-faq.html
# 
# awsElasticBlockStore:
#   fsType: ext4
#   volumeID: vol-xxxxxxxxx
