{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
{{- $namespace := $.Release.Namespace -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-gitlab-ci-pipelines-exporter-namespace
  namespace: {{ $namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
          {{ range .Values.istio.hardened.gcpe.namespaces }}
          - {{ . }}
          {{ end }}
{{- end }}

