{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.monitoring.enabled .Values.upstream.redis.metrics.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: monitoring-metrics-redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  action: ALLOW
  rules:
  - to:
    - operation:
        ports: ["9121"]
{{- end -}}