# This is an example values.yaml. It shows how to configure external object storage instead of the in-cluster minio provided by default
# https://gitlab.com/gitlab-org/charts/gitlab/tree/master/doc/advanced/external-object-storage
global:
  minio:
    enabled: false
  appConfig:
    artifacts:
      bucket: gitlab-artifacts-storage
    backups:
      bucket: gitlab-backup-storage
      tmpBucket: gitlab-tmp-storage
    ciSecureFiles:
      bucket: gitlab-ci-secure-files-storage
      enabled: true
    dependencyProxy:
      bucket: gitlab-dependency-proxy
      enabled: true
    externalDiffs:
      bucket: gitlab-external-diffs
      enabled: true
    lfs:
      bucket: gitlab-lfs-storage
    object_store:
      connection:
        secret: gitlab-object-storage
      enabled: true
      proxy_download: false
    packages:
      bucket: gitlab-packages-storage
    terraformState:
      bucket: gitlab-terraform-state-storage
      enabled: true
    uploads:
      bucket: gitlab-uploads-storage
  pages:
    enabled: true
    objectStore:
      enabled: true
      bucket: gitlab-pages-storage
      connection:
        secret: objectstore-pages
  registry:
    bucket: gitlab-registry-storage
gitlab:
  toolbox:
    backups:
      objectStorage:
        config:
          secret: s3cmd-config
          key: config
registry:
  storage:
    secret: registry-storage
    key: config
