{{- if .Values.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: gitlab-exporter
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - path: /sidekiq 
      interval: 30s
      port: http-metrics
      scheme: http
  jobLabel: gitlab
{{- end }}