# Dockerfile for registry.dso.mil/platform-one/big-bang/apps/developer-tools/gitlab/bbtests:0.0.3

FROM registry1.dso.mil/ironbank/google/golang/golang-1.16:1.16

# install crane
RUN go install github.com/google/go-containerregistry/cmd/crane@v0.5.1

CMD ["/bin/bash"]