apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: k8s
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab-exporter
  namespaceSelector:
    matchNames:
      - gitlab
  endpoints:
    - interval: 30s
      path: /sidekiq
      port: gitlab-exporter
      scheme: http
      jobLabel: gitlab
