# postgresql:
#   install: false

# nginx-ingress:
#   enabled: false

certmanager:
  install: false

# redis:
#   install: false

# registry:
#   enabled: false
#   ingress:
#     enabled: false

# Don't use this b/c it's still using extensions/v1beta1 for deployments 
prometheus:
  install: false

# Install separately with more configs
gitlab-runner:
  install: false

global:
  edition: ee
  hosts:
    domain: gitlab.kube.dev

  # NOTE: This doesn't work :|
  operator:
    enabled: false

  # psql:
  #   host: gitlab-cluster
  #   password:
  #     secret: gitlab.gitlab-cluster.credentials
  #     key: password
  #   port: 5432
  #   database: gitlab
  #   username: gitlab

  # redis:
  #   host: redis
  #   password:
  #     secret: redis
  #     key: redis-password
  #   port: 6379

  minio:
    enabled: true

  grafana:
    enabled: false

  imagePullPolicy: Always

  # kubectl:
  #   image:
  #     tag: 1.12.10-ubi8

  ingress:
    enabled: false
    configureCertmanager: false

  # See: https://gitlab.com/gitlab-org/charts/gitlab/tree/master/doc/advanced/external-object-storage
  # registry:
  #   bucket: my-registry-storage  # Registry storage bucket.

  # appConfig:
  #   lfs:
  #     bucket: my-lfs-storage  # LFS storage bucket.
  #     connection:
  #       # See: https://gitlab.com/gitlab-org/charts/gitlab/blob/master/doc/charts/globals.md#connection
  #       secret: my-objectstore-lfs-secret # LFS storage secret.
  #       key: connection
  #   artifacts:
  #     bucket: my-artifacts-storage # Artifacts storage bucket.
  #     connection:
  #       secret: my-objectstore-artifacts-secret # Artifacts storage secret.
  #       key: connection
  #   uploads:
  #     bucket: my-uploads-storage # Uploads storage bucket.
  #     connection:
  #       secret: my-objectstore-uploads-secret # Uploads storage secret.
  #       key: connection
  #   packages:
  #     bucket: my-packages-storage # Package storage bucket.
  #     connection:
  #       secret: my-objectstore-packages-secret # Package storage secret.
  #       key: connection
  #   backups:
  #     bucket: my-backup-storage # Backup storage bucket.
  #     tmpBucket: my-tmp-storage # Temp storage bucket.

gitlab:
  # gitaly:
  #   image:
  #     tag: master-ubi8

  # gitlab-exporter:
  #   image:
  #     tag: master-ubi8

  # gitlab-shell:
  #   image:
  #     tag: master-ubi8

  # gitlab-mailroom:
  #   image:
  #     tag: master-ubi8

  # migrations:
  #   image:
  #     tag: master-ubi8

  # sidekiq:
  #   image:
  #     tag: master-ubi8

  # task-runner:
  #   image:
  #     tag: master-ubi8

  #   # See: https://gitlab.com/gitlab-org/charts/gitlab/tree/master/doc/advanced/external-object-storage
  #   backups:
  #     objectStorage:
  #       config:
  #         secret: my-s3cmd-config # You config for 's3cmd'.
  #         key: config

  unicorn:
    minReplicas: 1
    maxReplicas: 1
    # image:
    #   tag: master-ubi8
    # workhorse:
    #   tag: master-ubi8
    helmTests:
      enabled: false
    ingress:
      enabled: false

upgradeCheck:
  enabled: false