{{- if $.Values.global.appConfig.smartcard.enabled -}}
{{- if eq (include "gitlab.ingress.enabled" $) "true" -}}
{{- $smartcardHostname := include "gitlab.smartcard.hostname" . -}}
{{- $tlsSecret := include "smartcard.tlsSecret" . -}}

apiVersion: {{ template "ingress.apiVersion" $}}
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-smartcard
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "{{ template "gitlab.ingressclass" . }}"
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.proxyBodySize | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.proxyReadTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.proxyConnectTimeout | quote }}
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: '2'
    nginx.ingress.kubernetes.io/auth-tls-secret: '{{ $.Release.Namespace }}/{{ $.Values.global.appConfig.smartcard.CASecret }}'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-SSL-Client-Certificate $ssl_client_escaped_cert;
    {{ include "gitlab.certmanager_annotations" . }}
  {{- range $key, $value := merge .Values.ingress.annotations .Values.global.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  rules:
    - host: {{ $smartcardHostname }}
      http:
        paths:
          - path: {{ coalesce $.Values.ingress.path $.Values.global.ingress.path }}
            {{ if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
            pathType: {{ default .ingress.pathType $.Values.global.ingress.pathType }}
            backend:
              service:
                  name: {{ template "fullname" . }}
                  port:
                    number: {{ .Values.service.workhorseExternalPort }}
            {{- else -}}
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: {{ .Values.service.workhorseExternalPort }}
            {{- end -}}
  {{- if (and $tlsSecret (eq (include "gitlab.ingress.tls.enabled" $) "true" )) }}
  tls:
    - hosts:
      - {{ $smartcardHostname }}
      secretName: {{ $tlsSecret }}
  {{- else }}
  tls: []
  {{- end }}
{{- end -}}
{{- end -}}
