# AWS Load Balancer Controller documentation
#   https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/annotations
#   https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/spec
#   https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/ingress_class

nginx-ingress:
  enabled: false

# Option 1: Use built-in AWS Load Balancer Controller IngressClass
global:
  ingress:
    class: none
    annotations:
      kubernetes.io/ingress.class: alb

# Option 2: Create a custom IngressClass
#   1. Create an IngressClass with a given name
#      - https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/ingress/spec
#   2. Set that class name under `global.ingress.class`
# global:
#   ingress:
#     class: foo
