# This is an example values.yaml. It shows how to configure incoming emails
global:
  appConfig:
    incomingEmail:
      enabled: true
      # This '+%{key}' suffix should be included in its entirety within the email
      # address and not replaced by another value.
      address: gitlab-incoming+%{key}@gmail.com
      host: example.com
      port: 993
      ssl: true
      startTls: true
      user: myusername
      password:
        # https://docs.gitlab.com/charts/installation/secrets.html#imap-password-for-incoming-emails#imap-password-for-incoming-emails
        # https://docs.gitlab.com/ee/development/emails.html
        secret: incoming-email-password
        key: secret
      mailbox: inbox
      deliveryMethod: webhook
      authToken: {}
