# This is an example values.yaml. It shows how to configure service desk email
# See https://docs.gitlab.com/ee/user/project/service_desk.html#using-custom-email-address
global:
  appConfig:
    incomingEmail:
      enabled: true
      # This '+%{key}' suffix should be included in its entirety within the email
      # address and not replaced by another value.
      address: gitlab-incoming+%{key}@gmail.com
      host: example.com
      port: 993
      ssl: true
      startTls: true
      user: myusername
      password:
        # https://docs.gitlab.com/charts/installation/secrets.html#imap-password-for-incoming-emails
        # https://docs.gitlab.com/ee/development/emails.html
        secret: my-incoming-mail-secret
        key: secret
      mailbox: inbox
      deliveryMethod: webhook
      authToken: {}
    serviceDeskEmail:
      enabled: true
      # This '+%{key}' suffix should be included in its entirety within the email
      # address and not replaced by another value.
      address: project_contact+%{key}@gmail.com
      host: example.com
      port: 993
      ssl: true
      startTls: true
      user: myusername
      password:
        # https://docs.gitlab.com/charts/installation/secrets.html#imap-password-for-service-desk-emails
        # https://docs.gitlab.com/ee/development/emails.html
        secret: service-desk-email-password
        key: secret
      mailbox: inbox
      deliveryMethod: webhook
      authToken: {}
