{{- if index .Values "gitlab-ci-pipelines-exporter" "enabled" }}
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: exporter-token-sa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
{{- end }}
