# TODO: Use external postgresql
postgresql:
  install: false

registry:
  enabled: true
  host: registry-gitlab
  #authEndpoint: http://gitlab-webservice.gitlab.svc.cluster.local:8181
  storage:
    secret: registry-storage
    key: config
  ingress:
    enabled: false

# Use istio instead
nginx-ingress:
  enabled: false

# lol I wish
certmanager:
  install: false

# Install gitlab-runner seperately
gitlab-runner:
  install: false

global:
  edition: ee
  ingress:
    enabled: false
    configureCertmanager: false
  hosts:
    domain: "code.dsop.io"
    gitlab:
      name: "code.dsop.io"

#   registry:
#     bucket: gitlab-registry-storage

  # Use external postgresql
  psql:
    host: db.admin.dsop.io
    port: 5432
    username: rdsuser
    database: gitlab
    password:
      secret: db-credentials
      key: PGPASSWORD

  # Uncomment for External Minio (S3)
  # minio:
  #   enabled: false
  # appConfig:
  #   lfs:
  #     bucket: $ARGOCD_APP_SOURCE_TARGET_REVISION-t-rex-bootstrap-p1-k8s-gitlab-storage
  #     connection:
  #       secret: s3-creds
  #       key: rails
  #   artifacts:
  #     bucket: $ARGOCD_APP_SOURCE_TARGET_REVISION-t-rex-bootstrap-p1-k8s-gitlab-storage
  #     connection:
  #       secret: s3-creds
  #       key: rails
  #   uploads:
  #     bucket: $ARGOCD_APP_SOURCE_TARGET_REVISION-t-rex-bootstrap-p1-k8s-gitlab-storage
  #     connection:
  #       secret: s3-creds
  #       key: rails
  #   packages:
  #     bucket: $ARGOCD_APP_SOURCE_TARGET_REVISION-t-rex-bootstrap-p1-k8s-gitlab-storage
  #     connection:
  #       secret: s3-creds
  #       key: rails
  #   backups:
  #     bucket: $ARGOCD_APP_SOURCE_TARGET_REVISION-t-rex-bootstrap-p1-k8s-gitlab-storage
  #     connection:
  #       secret: s3-creds
  #       key: rails

  grafana:
    enabled: false

gitlab:
  # Disable for shell
  # gitlab-shell:
  #   enabled: false

  webservice:
    helmTests:
      enabled: false

    ingress:
      enabled: false

    webservice:
      registry:
        enabled: false

  gitaly:
    persistence:
      size: 50Gi

  task-runner:
    backups:
      objectStorage:
        config:
          secret: s3-creds
          key: backup

    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
