{{- $processedDict := dict -}}
{{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/**" }}
{{- $name := trimPrefix "bigbang/DoD_CA_certs/" (dir $path) }}
{{- if not (hasKey $processedDict $name) -}}
{{ $_ := set $processedDict $name "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ (lower (printf "ca-certs-%s" (trimPrefix "_" $name))) | replace "_" "-" | replace "/" "-" | replace " " "-" }}
  namespace: {{ $.Release.Namespace }}
data:
  {{- range $filepath, $filebytes := $.Files.Glob (printf "%s/*" (dir $path)) }}
  {{ ($.Files.Glob $filepath ).AsSecrets }}
  {{- end }}
---
{{- end }}
{{- end }}