# DoD Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-email-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD/Intermediate_and_Issuing_CA_Certs/*DOD_EMAIL_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-id-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD/Intermediate_and_Issuing_CA_Certs/*DOD_ID_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-sw-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD/Intermediate_and_Issuing_CA_Certs/*SW_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-derility-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD/Intermediate_and_Issuing_CA_Certs/*DOD_DERILITY_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-trust-anchors
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD/Trust_Anchors_Self-Signed/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# ECA Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-eca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_ECA/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Austrailian Defence Organization Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-ado-cc-chain
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Australian_Defence_Organisation/Cross_Cert_Chain/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-ado-dt-chain
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Australian_Defence_Organisation/Direct_Trust_Chain/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Boeing Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-boeing
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Boeing/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Carillon Federal Services Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-carillon-federal-services
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Carillon_Federal_Services/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Department Of State Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-department-of-state-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Department_of_State/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-department-of-state-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Department_of_State/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# DigiCert Federal SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-digicert-federal-ssp-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/DigiCert_Federal_SSP/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-digicert-federal-ssp-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/DigiCert_Federal_SSP/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# DigiCert NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-digicert-nfi
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/DigiCert_NFI/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Entrust Federal SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-entrust-federal-ssp-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Entrust_Federal_SSP/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-entrust-federal-ssp-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Entrust_Federal_SSP/Trust_Chain_2/1-*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Enstrust Managed Service NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-entrust-managed-servcie-nfi
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Entrust_Managed_Service_NFI/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Exostar LLC Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-exostar-llc
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Exostar_LLC/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# IdenTrust NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-identrust-nfi
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/IdenTrust_NFI/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Lockheed Martin Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-lockheed-martin
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Lockheed_Martin/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Netherlands Ministry Of Defense Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-netherlands-mod
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Netherlands_Ministry_of_Defence/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Northrop Grumman Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-northrop-grumman
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Northrop_Grumman/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Raytheon Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-raytheon-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Raytheon/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-raytheon-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Raytheon/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Treasury SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-us-treasury-ssp-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/US_Treasury_SSP/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-us-treasury-ssp-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/US_Treasury_SSP/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Verizon Cybertrust Federal SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-verizon-cybertrust-federal-ssp
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Verizon_Cybertrust_Federal_SSP/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# WidePoint Federal SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-widepoint-federal-ssp-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/WidePoint_Federal_SSP/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-widepoint-federal-ssp-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/WidePoint_Federal_SSP/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# WidePoint NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-widepoint-nfi-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/WidePoint_NFI/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-widepoint-nfi-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/WidePoint_NFI/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
