# DoD Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-trust-anchors
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD_Certs/Trust_Anchors_Self-Signed/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-email-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD_Certs/Intermediate_and_Issuing_CA_Certs/*DOD_EMAIL_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-id-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD_Certs/Intermediate_and_Issuing_CA_Certs/*DOD_ID_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-id-sw-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD_Certs/Intermediate_and_Issuing_CA_Certs/*DOD_ID_SW_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-dod-intermediate-dod-sw-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_DoD_Certs/Intermediate_and_Issuing_CA_Certs/*DOD_SW_CA*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# ECA Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-eca-sha-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_ECA_Certs/SHA-1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-eca-sha-256
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/_ECA_Certs/SHA-256/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# ADO Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-ado-sha-256-cc-chain
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/ADO/SHA-256/Cross_Cert_Chain/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-ado-sha-256-dt-chain
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/ADO/SHA-256/Direct_Trust_Chain/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Boeing Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-boeing-sha-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Boeing/SHA-1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Carillon Federal Services Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-carillon-federal-services
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Carillon-Federal-Services/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Department Of State Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-department-of-state-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Department_of_State/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-department-of-state-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Department_of_State/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Entrust NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-entrust-nfi-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Entrust_NFI/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-entrust-nfi-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Entrust_NFI/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Entrust SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-entrust-ssp
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Entrust_SSP/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Exostar LLC Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-exostar-llc
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Exostar_LLC/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# IdenTrust NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-identrust-nfi
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/IdenTrust_NFI/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Lockheed Martin Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-lockheed-martin-sha-256
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Lockheed_Martin/SHA-256/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# NL MOD Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-nl-mod
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/NL_MOD/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Northrop Grumman Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-northrop-grumman-sha-256
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Northrop_Grumman/SHA-256/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# ORC NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-orc-nfi
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/ORC_NFI/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# ORC SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-orc-ssp
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/ORC_SSP/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Raytheon Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-raytheon-sha-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Raytheon/SHA-1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-raytheon-sha-256
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Raytheon/SHA-256/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Symantec NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-symantec-nfi-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Symantec_NFI/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-symantec-nfi-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Symantec_NFI/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Symantec SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-symantec-ssp-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Symantec_SSP/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-symantec-ssp-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Symantec_SSP/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Treasury SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-treasury-ssp-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Treasury_SSP/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-treasury-ssp-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Treasury_SSP/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Verizon Business NFI Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-verizon-business-nfi
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Verizon_Business_NFI/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
# Verizon Business SSP Certificate Authorities
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-verizon-business-ssp-trust-chain-1
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Verizon_Business_SSP/Trust_Chain_1/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-certs-verizon-business-ssp-trust-chain-2
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- $files := .Files }}
  {{- range $path, $bytes := .Files.Glob "bigbang/DoD_CA_certs/Verizon_Business_SSP/Trust_Chain_2/*.cer" }}
  {{- $filename := trimSuffix (ext $path) (base $path) }}
  {{ $filename }}: |-
    {{- $files.Get $path | nindent 4 }}
  {{- end }}
