# frozen_string_literal: true

issuer_job_changed = helper.all_changed_files.any?('charts/certmanager-issuer/templates/issuer-job.yaml')
chart_yaml_changed = helper.all_changed_files.any?('charts/certmanager-issuer/Chart.yaml')

if issuer_job_changed && !chart_yaml_changed
  failure <<~MSG
   Jobs templates are immutable. Changing it breaks upgrades if there's an existing job with the same name.
   Please bump the certmanager-issuer chart version, so that it gets a different generated name
   as per [globals Jobs documentation](https://docs.gitlab.com/charts/charts/globals.html#jobs).
  MSG
end
