# frozen_string_literal: true

if helper.all_changed_files.detect(-> { false }) { |filename| filename == 'charts/certmanager-issuer/templates/issuer-job.yaml' }
  failure <<~MSG
   Jobs templates are immutable. Changing it breaks upgrades if there's an existing job with the same name.
   Please bump the certmanager-issuer chart version, so that it gets a different generated name
   as per [globals Jobs documentation](https://docs.gitlab.com/charts/charts/globals.html#jobs).
  MSG
end
