trigger_operator_test:
  stage: approve-review-apps
  trigger:
    project: 'gitlab-org/cloud-native/gitlab-operator'
    branch: master
  variables:
    CHARTS_REF: "${CI_COMMIT_SHA}"
    TRIGGER_PROJECT: "${CI_PROJECT_PATH}"
    PIPELINE_TYPE: "${PIPELINE_TYPE}"
  inherit:
    variables: false
  rules:
    - if: '$PIPELINE_TYPE == "DOCS_PIPELINE"'
      when: never
    - when: manual
