trigger_operator_test:
  stage: approve-review-apps
  trigger:
    project: 'gitlab-org/cloud-native/gitlab-operator'
    branch: master
  variables:
    CHARTS_REF: "${CI_COMMIT_SHA}"
    TRIGGER_PROJECT: "${CI_PROJECT_PATH}"
  inherit:
    variables: false
  allow_failure: true
  rules:
    - !reference [.rule:skip_docs_pipeline]
    - !reference [.rule:skip_if_not_canonical_or_security]
    - when: manual
