---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitlab-ssh-virtual-service
spec:
  hosts:
    - "gitlab.kube.dev"
  gateways:
    - public-gateway.istio-system.svc.cluster.local
  tcp:
    - match:
        - port: 22
      route:
        - destination:
            host: gitlab-gitlab-shell.gitlab.svc.cluster.local
            port:
              number: 22

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitlab-ui-virtual-service
spec:
  hosts:
    - "gitlab.kube.dev"
    # - gitlab.${MY_DOMAIN}
  gateways:
    - public-gateway.istio-system.svc.cluster.local
  http:
    - route:
      - destination:
          host: gitlab-unicorn.gitlab.svc.cluster.local
          port:
            number: 8181
      match:
      - url:
          prefix: /
      websocketUpgrade: true
    - match:
      - uri:
          prefix: /admin/sidekiq
      route:
      - destination:
          host: gitlab-unicorn.gitlab.svc.cluster.local
          port:
            number: 8080
  tcp:
  - match:
    - port: 22
    route:
    - destination:
        host: gitlab-gitlab-shell.gitlab.svc.cluster.local
        port:
          number: 22
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: gitlab-minio-virtual-service
# spec:
#   hosts:
#     - "*"
#     # - minio.${MY_DOMAIN}
#   gateways:
#     - gitlab-gateway
#   http:
#     - route:
#         - destination:
#             host: gitlab-minio-svc.gitlab.svc.cluster.local
#             port:
#               number: 9000

---

# TODO: Need this until we get some sidecar injection going
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gitlab-ui
spec:
  host: gitlab-unicorn.gitlab.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---

# TODO: Need this until we get some sidecar injection going
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gitlab-ssh
spec:
  host: gitlab-unicorn.gitlab.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
