---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gitlab-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    # - port:
        # number: 22
        # name: ssh-gitlab
        # protocol: TCP
      # hosts:
      #   - gitlab.${MY_DOMAIN}
    - port:
        number: 80
        name: http-gitlab
        protocol: HTTP
      hosts:
        - "*"
      # tls:
      #   httpsRedirect: true
    # - port:
    #     number: 443
    #     name: https-gitlab
    #     protocol: HTTPS
      # hosts:
      #   - gitlab.${MY_DOMAIN}
      #   - minio.${MY_DOMAIN}
      # tls:
      #   credentialName: ingress-cert-${LETSENCRYPT_ENVIRONMENT}
      #   mode: SIMPLE
      #   privateKey: sds
      #   serverCertificate: sds
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: gitlab-ssh-virtual-service
# spec:
#   hosts:
#     - "*"
#     # - gitlab.${MY_DOMAIN}
#   gateways:
#     - gitlab-gateway
#   tcp:
#     - match:
#         - port: 22
#       route:
#         - destination:
#             host: gitlab-gitlab-shell.gitlab.svc.cluster.local
#             port:
#               number: 22
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitlab-http-virtual-service
spec:
  hosts:
    - "*"
    # - gitlab.${MY_DOMAIN}
  gateways:
    - gitlab-gateway
  http:
    - route:
        - destination:
            host: gitlab-unicorn.gitlab.svc.cluster.local
            port:
              number: 8181
      match:
        - url:
            prefix: /
    - match:
        - uri:
            prefix: /admin/sidekiq
      route:
        - destination:
            host: gitlab-unicorn.gitlab.svc.cluster.local
            port:
              number: 8080
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: gitlab-minio-virtual-service
# spec:
#   hosts:
#     - "*"
#     # - minio.${MY_DOMAIN}
#   gateways:
#     - gitlab-gateway
#   http:
#     - route:
#         - destination:
#             host: gitlab-minio-svc.gitlab.svc.cluster.local
#             port:
#               number: 9000

---

# TODO: Need this until we get some sidecar injection going
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: gitlab-destination
  namespace: gitlab
spec:
  host: gitlab-unicorn.gitlab.svc.cluster.local
