{{- if and (eq .Values.controller.kind "Deployment") .Values.controller.autoscaling.enabled (not .Values.controller.keda.enabled) -}}
{{- $hpaCfg := (dict "global" $.Values.global.hpa "local" .Values.controller.autoscaling "context" $) -}}
apiVersion: {{ template "gitlab.hpa.apiVersion" $hpaCfg }}
kind: HorizontalPodAutoscaler
metadata:
  {{- with .Values.controller.autoscaling.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    component: "{{ .Values.controller.name }}"
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ingress-nginx.controller.fullname" . }}
  namespace: {{ include "ingress-nginx.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ingress-nginx.controller.fullname" . }}
  minReplicas: {{ .Values.controller.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.controller.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.controller.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      {{- if (include "gitlab.hpa.supportsV2MetricsSpec" $hpaCfg) }}
      target:
        type: Utilization
        averageUtilization: {{ . }}
      {{- else }}
      targetAverageUtilization: {{ . }}
      {{- end }}
  {{- end }}
  {{- with .Values.controller.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      {{- if (include "gitlab.hpa.supportsV2MetricsSpec" $hpaCfg) }}
      target:
        type: Utilization
        averageUtilization: {{ . }}
      {{- else }}
      targetAverageUtilization: {{ . }}
      {{- end }}
  {{- end }}
  {{- with .Values.controller.autoscalingTemplate }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- include "gitlab.hpa.behavior" $hpaCfg | nindent 2 }}
{{- end }}
