{{- if and .Values.tcp (not .Values.tcpExternalConfig) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    component: "{{ .Values.controller.name }}"
    app.kubernetes.io/component: controller
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- if .Values.controller.tcp.annotations }}
  annotations: {{ toYaml .Values.controller.tcp.annotations | nindent 4 }}
{{- end }}
  name: {{ template "ingress-nginx.tcp-configmap" . }}
  namespace: {{ include "ingress-nginx.namespace" . }}
data: {{ tpl (toYaml .Values.tcp) . | nindent 2 }}
{{- end }}
