{{- if and .Values.defaultBackend.enabled .Values.defaultBackend.autoscaling.enabled }}
{{- $hpaCfg := (dict "global" $.Values.global.hpa "local" .Values.backendConfig.autoscaling "context" $) -}}
apiVersion: {{ template "gitlab.hpa.apiVersion" $hpaCfg }}
kind: HorizontalPodAutoscaler
metadata:
  {{- with .Values.defaultBackend.autoscaling.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    component: "{{ .Values.defaultBackend.name }}"
    app.kubernetes.io/component: default-backend
    {{- with .Values.defaultBackend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ingress-nginx.defaultBackend.fullname" . }}
  namespace: {{ include "ingress-nginx.namespace" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ingress-nginx.defaultBackend.fullname" . }}
  minReplicas: {{ .Values.defaultBackend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.defaultBackend.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.defaultBackend.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      {{- if (include "gitlab.hpa.supportsV2MetricsSpec" $hpaCfg) }}
      target:
        type: Utilization
        averageUtilization: {{ . }}
      {{- else }}
      targetAverageUtilization: {{ . }}
      {{- end }}
  {{- end }}
  {{- with .Values.defaultBackend.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      {{- if (include "gitlab.hpa.supportsV2MetricsSpec" $hpaCfg) }}
      target:
        type: Utilization
        averageUtilization: {{ . }}
      {{- else }}
      targetAverageUtilization: {{ . }}
      {{- end }}
  {{- end }}
  {{- include "gitlab.hpa.behavior" $hpaCfg | nindent 2 }}
{{- end }}
