{{- if and .Values.defaultBackend.enabled .Values.defaultBackend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    component: "{{ .Values.defaultBackend.name }}"
    app.kubernetes.io/component: default-backend
    {{- with .Values.defaultBackend.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "ingress-nginx.defaultBackend.serviceAccountName" . }}
  namespace: {{ include "ingress-nginx.namespace" . }}
{{ include "ingress-nginx.defaultBackend.automountServiceAccountToken" . }}
{{- end }}
