{{- $externalAddresses := concat $.Values.global.pages.externalHttp $.Values.global.pages.externalHttps | uniq }}
{{- if not (empty ($externalAddresses)) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-custom-domains
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "gitlab.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "gitlab.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.customDomains.type }}
  {{- if eq .Values.service.customDomains.type "LoadBalancer" }}
  {{- if not (empty ($externalAddresses)) -}}
  {{-   if len $externalAddresses | eq 1 }}
  loadBalancerIP: {{ $externalAddresses | first }}
  {{-   else }}
  externalIPs: {{ toJson $externalAddresses }}
  {{-   end }}
  {{- end }}
  {{- end }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.internalPort | int }}
      protocol: TCP
      name: http-{{ template "name" . }}
      {{- if and (eq .Values.service.customDomains.type "NodePort") .Values.service.customDomains.nodePort.http }}
      nodePort: {{ .Values.service.customDomains.nodePort.http | int }}
      {{- end }}
    - port: 443
      targetPort: {{ .Values.service.customDomains.internalHttpsPort | int }}
      protocol: TCP
      name: https-{{ template "name" . }}
      {{- if and (eq .Values.service.customDomains.type "NodePort") .Values.service.customDomains.nodePort.https }}
      nodePort: {{ .Values.service.customDomains.nodePort.https | int }}
      {{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
{{- end -}}
