{{- if and .Values.istio.enabled .Values.istio.gitlab.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.istio.gitlab.labels }}
      {{ toYaml .Values.istio.gitlab.labels | indent 4 }}
    {{- end }}
    app.kubernetes.io/component: "gitlab"
  {{- if .Values.istio.gitlab.annotations }}
  annotations:
    {{ toYaml .Values.istio.gitlab.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.gitlab.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- if .Values.istio.gitlab.hosts }}
  {{- range .Values.istio.gitlab.hosts }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - "{{ .Values.global.hosts.gitlab.name }}"
  {{- end }}
  http:
    - fault:
        abort:
          httpStatus: 403
          percentage:
            value: 100
      match:
      - uri:
          prefix: /-/metrics
      route:
      - destination:
          host: {{ .Release.Name }}-webservice-default.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8181
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: {{ .Release.Name }}-webservice-default.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8181
    - match:
      - uri:
          prefix: /admin/sidekiq
      route:
      - destination:
          host: {{ .Release.Name }}-webservice-default.{{ .Release.Namespace }}.svc.cluster.local
          port:
            number: 8080
{{- end }}
{{- if and .Values.istio.enabled .Values.istio.registry.enabled }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.istio.registry.labels }}
      {{ toYaml .Values.istio.registry.labels | indent 4 }}
    {{- end }}
    app.kubernetes.io/component: "gitlab"
  {{- if .Values.istio.registry.annotations }}
  annotations:
    {{ toYaml .Values.istio.registry.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.registry.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- if .Values.istio.registry.hosts }}
  {{- range .Values.istio.registry.hosts }}
    - {{ . | quote }}
  {{- end }}
  {{- else }}
    - "{{ .Values.global.hosts.registry.name }}"
  {{- end }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Release.Name }}-registry.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 5000
{{- end }}
