{{ if and .Values.istio.enabled (eq .Values.istio.injection "enabled") (eq .Values.istio.mtls.mode "STRICT") }}
{{- if or (not (hasKey .Values.minio "enabled")) .Values.minio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gitlab-minio-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: minio
  portLevelMtls:
    "9000":
      mode: PERMISSIVE
{{- end }}
{{- end }}
