# metrics for gitlab but only when gitlab runner is enabled
{{ if and .Values.istio.enabled (eq .Values.istio.injection "enabled") (eq .Values.istio.mtls.mode "STRICT") .Values.monitoring.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gitlab-runner-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: gitlab-runner
  portLevelMtls:
    "9252":
      mode: PERMISSIVE
{{- end }}
