{{ if and .Values.istio.enabled (eq .Values.istio.injection "enabled") (eq .Values.istio.mtls.mode "STRICT") }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gitlab-metrics-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: gitlab-exporter
  portLevelMtls:
    "9168":
      mode: PERMISSIVE
{{- end }}
---
# metrics for gitlab but only when gitlab runner is enabled
{{ if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gitlab-metrics-runner-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: gitlab-runner-gitlab-runner
  portLevelMtls:
    "9252":
      mode: PERMISSIVE
{{- end }}
