{{ if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: gitlab-redis-exception
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
  selector:
    matchLabels:
      app: redis
  portLevelMtls:
    "6379":
      mode: PERMISSIVE
    "9121":
      mode: PERMISSIVE
{{- end }}