include:
  - component: "gitlab.com/gitlab-org/quality/pipeline-common/allure-report@9.6.3"
    inputs:
      job_name: "e2e-test-gke131a"
      job_stage: "qa-report"
      gitlab_auth_token_variable_name: "DANGER_GITLAB_API_TOKEN"
      aws_access_key_id_variable_name: "QA_ALLURE_AWS_ACCESS_KEY_ID"
      aws_secret_access_key_variable_name: "QA_ALLURE_AWS_SECRET_ACCESS_KEY"
      allure_results_glob: "gitlab-qa-run-*/**/allure-results"
    rules:
      - if: '$CI_SERVER_HOST != "gitlab.com"'
        when: never
      - if: '$CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "parent_pipeline"'

.review_gke131a_common_vars: &review_gke131a_common_vars
  DNS_PROVIDER: "google"
  AGENT_NAME: "gke131-ci-cluster"
  KUBE_INGRESS_BASE_DOMAIN: "cloud-native-v131.helm-charts.win"
  KUBE_NAMESPACE: "helm-charts-win"
  DEPLOY_MULTIARCH: "true"

create_review_gke131a:
  stage: review
  image: ${BUSYBOX_IMAGE}
  variables:
    <<: *review_gke131a_common_vars
    GIT_STRATEGY: none
  script:
    - echo "Configuring gke131_review/a-$REVIEW_REF_PREFIX$CI_COMMIT_SHORT_SHA to automatically stop in $REVIEW_APPS_AUTO_STOP_IN."
  environment: &gke131a_environment
    name: &gke131a_name gke131_review/a-$REVIEW_REF_PREFIX$CI_COMMIT_SHORT_SHA
    url: https://gitlab-$CI_ENVIRONMENT_SLUG.$KUBE_INGRESS_BASE_DOMAIN
    on_stop: stop_review_gke131a
    auto_stop_in: $REVIEW_APPS_AUTO_STOP_IN
    action: start

review_gke131a:
  variables:
    <<: *review_gke131a_common_vars
  extends: .review_template
  environment:
    <<: *gke131a_environment
    action: access
  # initially allow arm64 failures
  allow_failure: true

stop_review_gke131a:
  variables:
    <<: *review_gke131a_common_vars
  extends: .stop_review_template
  # initially allow arm64 failures
  allow_failure: true
  environment:
    # name: gke131_review/a-$REVIEW_REF_PREFIX$CI_COMMIT_SHORT_SHA
    name: *gke131a_name
    action: stop

review_specs_gke131a:
  extends: .specs
  variables:
    <<: *review_gke131a_common_vars
    VARIABLES_FILE: "variables/review_gke131a"
    RSPEC_TAGS: type:feature
  # initially allow arm64 failures
  allow_failure: true
  environment:
    <<: *gke131a_environment
    action: access
  rules:
    - !reference [.rule:skip_if_no_cluster]
    - !reference [.specs, rules]
  needs: ["review_gke131a"]

qa_gke131a:
  extends: .qa_branch
  variables:
    VARIABLES_FILE: "variables/review_gke131a"
    TEST_SUITE: $QA_SANITY_SUITE_OPTIONS
  # initially allow arm64 failures
  allow_failure: true
  environment:
    <<: *gke131a_environment
    action: access
  needs:
    - review_gke131a
    - job: review_specs_gke131a
      artifacts: false

qa_gke131a_full_suite_manual_trigger:
  extends: .qa_full_suite_manual_trigger
  script: echo 'The job will trigger Full E2E suite against GKE131'

qa_gke131a_manual_full_suite:
  extends: .qa_branch
  parallel: 7
  variables:
    VARIABLES_FILE: "variables/review_gke131a"
    TEST_SUITE: $QA_FULL_SUITE_OPTIONS
  # initially allow arm64 failures
  allow_failure: true
  environment:
    <<: *gke131a_environment
    action: access
  needs: ["qa_gke131a_full_suite_manual_trigger"]
