include:
  - component: "gitlab.com/gitlab-org/quality/pipeline-common/allure-report@9.6.3"
    inputs:
      job_name: "e2e-test-gkevc131"
      job_stage: "qa-report"
      gitlab_auth_token_variable_name: "DANGER_GITLAB_API_TOKEN"
      aws_access_key_id_variable_name: "QA_ALLURE_AWS_ACCESS_KEY_ID"
      aws_secret_access_key_variable_name: "QA_ALLURE_AWS_SECRET_ACCESS_KEY"
      allure_results_glob: "gitlab-qa-run-*/**/allure-results"
    rules:
      - if: '$CI_SERVER_HOST != "gitlab.com"'
        when: never
      - if: '$CI_PIPELINE_SOURCE == "pipeline" || $CI_PIPELINE_SOURCE == "parent_pipeline"'

.review_gkevc131_common_vars: &review_gkevc131_common_vars
  VCLUSTER_K8S_VERSION: "v1.31.0"
  VCLUSTER_NAME: "vc131-${REVIEW_REF_PREFIX}${CI_COMMIT_SHORT_SHA}"
  HOST_SUFFIX: "${CI_ENVIRONMENT_SLUG}-vc131"
  # the VARIABLES_FILE value is from the CI_JOB_NAME of the review job
  VARIABLES_FILE: "variables/review_gkevc131"
  DOMAIN: "-${HOST_SUFFIX}.${KUBE_INGRESS_BASE_DOMAIN}"

create_review_gkevc131:
  stage: review
  image: ${BUSYBOX_IMAGE}
  variables:
    <<: *review_gkevc131_common_vars
    GIT_STRATEGY: none
  script:
    - echo "Configuring gkevc_review/$REVIEW_REF_PREFIX$CI_COMMIT_SHORT_SHA to automatically stop in $REVIEW_APPS_AUTO_STOP_IN."
  environment: &gkevc131_environment
    name: &gkevc131_name gkevc_review/$REVIEW_REF_PREFIX$CI_COMMIT_SHORT_SHA
    url: "https://gitlab${DOMAIN}"
    on_stop: stop_review_gkevc131
    auto_stop_in: $REVIEW_APPS_AUTO_STOP_IN
    action: start

review_gkevc131:
  variables:
    <<: *review_gkevc131_common_vars
  extends: .vcluster_review_template
  environment:
    <<: *gkevc131_environment
    action: access

stop_review_gkevc131:
  variables:
    <<: *review_gkevc131_common_vars
  extends: .stop_vcluster_review_template
  environment:
    name: *gkevc131_name
    action: stop

review_specs_gkevc131:
  extends: .vcluster_specs_template
  variables:
    <<: *review_gkevc131_common_vars
  environment:
    <<: *gkevc131_environment
    action: access
  needs: ['review_gkevc131']

qa_gkevc131:
  extends: .qa_branch
  variables:
    <<: *review_gkevc131_common_vars
    TEST_SUITE: $QA_SANITY_SUITE_OPTIONS
  environment:
    <<: *gkevc131_environment
    action: access
  needs:
    - review_gkevc131
    - job: review_specs_gkevc131
      artifacts: false

qa_gkevc131_full_suite_manual_trigger:
  extends: .qa_full_suite_manual_trigger
  script: echo 'The job will trigger Full E2E suite against GKE131 vcluster'

qa_gkevc131_manual_full_suite:
  extends: .qa_branch
  parallel: 7
  variables:
    <<: *review_gkevc131_common_vars
    TEST_SUITE: $QA_FULL_SUITE_OPTIONS
  environment:
    <<: *gkevc131_environment
    action: access
  needs: ["qa_gkevc131_full_suite_manual_trigger"]
