apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "shared-secrets.jobname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ template "shared-secrets.serviceAccountName" . }}
      {{- end }}
      restartPolicy: Never
      {{- include "pullsecrets" .Values.global.kubectl.image | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "gitlab.kubectl.image" . | quote }}
          command: ['/bin/bash', '/scripts/generate-secrets']
          {{ template "gitlab.imagePullPolicy" . }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: ssh
              mountPath: /etc/ssh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: scripts
        configMap:
          name: {{ template "fullname" . }}
      - name: ssh
        emptyDir: {}
