apiVersion: v1
# GitLab: changed name here from `ingress-nginx` to match the previous versions
# to avoid a breaking change for the time being.
name: nginx-ingress
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 3.11.1
appVersion: 0.41.2
home: https://github.com/kubernetes/ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
keywords:
  - ingress
  - nginx
sources:
  - https://github.com/kubernetes/ingress-nginx
  - https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/nginx-ingress
maintainers:
  - name: ChiefAlexander
engine: gotpl
kubeVersion: ">=1.16.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx?modal=changelog
  artifacthub.io/changes: |
    - Reorder HPA resource list to work with GitOps tooling
