postgresql:
  image:
    tag: 14

registry:
  database:
    enabled: true
    password:
      secret: testing-postgresql-password
      key: registry-password
    name: registry_testing
    host: testing.postgresql
    port: 9999
