global:
  registry:
    notifications:
      endpoints:
        - name: gitlab
          # DEPRECATED: use `maxretries` instead https://gitlab.com/gitlab-org/container-registry/-/issues/1243.
          # When using `maxretries`, `threshold` is ignored: https://gitlab.com/gitlab-org/container-registry/-/blob/master/docs/configuration.md?ref_type=heads#endpoints
          threshold: 10
          maxretries: 5
          backoff: 1s
          headers:
            Authorization:
              secret: gitlab-registry-authorization-header-v1
              key: secret
          ignore:
            actions:
              - pull
          ignoredmediatypes:
            - application/octet-stream
          timeout: 500ms
