# NOTE: Generator below is used a reference only, due to the nature of helm and generators, we don't use this `package` as _the_ base
# generators:
#   - chart.yaml

# Reference: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/plugins/builtins.md#field-name-patches
patches:
  # Replace all helm hooks in "shared-secrets" subchart with appropriate ArgoCD hooks
  # NOTE: While in most cases this isn't necessary, Gitlab relies on Helm hooks to delete certain sensitive resources once they have succeeded
  #       In helm land, this delete happens after all resources have synced, in ArgoCD land, this happens after each resource has synced
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: PostSync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
    target:
      labelSelector:  "app=shared-secrets"
  # Replace all helm hooks in the upgrade check with appropriate ArgoCD hooks
  - patch: |-
      - op: replace
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: PostSync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
    target:
      name: gitlab-gitlab-upgrade-check
      annotationSelector:  "helm.sh/hook=pre-upgrade"
