# EXTERNAL RDS
# EXTERNAL MINIO
# EXTERNAL REDIS
# NO NGINX CONTROLLER

# TODO: Use external postgresql
postgresql:
  install: false

registry:
  enabled: true
  host: registry-gitlab
  #authEndpoint: http://gitlab-unicorn.gitlab.svc.cluster.local:8181
  storage:
    secret: registry-storage
    key: config
  ingress:
    enabled: false

nginx-ingress:
  enabled: false

certmanager:
  install: false

# TODO: Use external redis
# redis:
#  install: false

prometheus:
  install: false

gitlab-runner:
  install: false

global:
  edition: ee
  hosts:
    domain: "gitlab.dsop.io"
    gitlab:
      name: gitlab

  registry:
    bucket: gitlab-registry-storage

  # TODO: Use external postgresql
  psql:
    password:
      secret: db-credentials
      key: PGPASSWORD
    port: 5432
    database: gitlab

  # TODO: Use external redis
#  redis:
#    host: '$(REDIS_HOST)'
#    password:
#      enabled: true
#      secret: redis-secret
#      key: redis-password
#    port: 6379

  minio:
    enabled: false
  appConfig:
    lfs:
      bucket: gitlab-backups
      connection:
        secret: object-storage
        key: connection
    artifacts:
      bucket: gitlab-backups
      connection:
        secret: object-storage
        key: connection
    uploads:
      bucket: gitlab-backups
      connection:
        secret: object-storage
        key: connection
    packages:
      bucket: gitlab-backups
      connection:
        secret: object-storage
        key: connection
    backups:
      bucket: gitlab-backups
      connection:
        secret: object-storage
        key: connection

  grafana:
    enabled: false

  imagePullPolicy: Always

  ingress:
    enabled: false
    configureCertmanager: false

gitlab:
  gitlab-shell:
    enabled: false

  unicorn:
    helmTests:
      enabled: false

    ingress:
      enabled: false

    unicorn:
      registry:
        enabled: false

  task-runner:
    backups:
      objectStorage:
        config:
          secret: s3cmd-config
          key: config
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi

upgradeCheck:
  enabled: true
